---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
            exclude: (.vscode|.devcontainer)
          - id: check-yaml
          - id: detect-private-key
          - id: check-added-large-files
            args: ['--maxkb=950']
    # Commeting it out as it wrongly formats teh files
    # - repo: https://github.com/MarketSquare/robotframework-tidy
    #   rev: 1.4.0
    #   hooks:
    #       - id: robotidy
    #         name: robotidy
    #         entry: robotidy
    #         files: '.*\.(robot|resource)$'
    #         language: python
    #         description: "RobotFramework source code formatter"

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.17.13
      hooks:
          - id: commitizen
            stages: [commit-msg]

    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v5.0.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@commitlint/config-conventional']

    - repo: https://github.com/gitguardian/gg-shield
      rev: v1.7.3
      hooks:
          - id: ggshield
            language_version: python3
            stages: [commit]
